### ISSUE TITLE
Python or R API calls to BlueDB

### ISSUE THREAD

**Issue by aakbarie** [BlueDB/BlueDB#163]
Is there a way to query BlueDB through Python or R

**Comment by bradj** [comment]
I'd also like to know :)

**Comment by d-w-johnson** [comment]
No sorry. It is meant to be embedded into a Java application. The data is stored on the file system as serialized Java objects using https://github.com/RuedigerMoeller/fast-serialization in order to facilitate fast, low memory, chronological read queries in Java applications. You would need to embed it into a Java application that exposes a custom API
